name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  auto_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Main Workflow
        uses: "actions/github-script@v5"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflows } = await github.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const mainWorkflow = workflows.find(workflow => workflow.name === 'Deploy');

            if (mainWorkflow) {
              await github.actions.reRunWorkflow({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: mainWorkflow.id,
              });
            }
