name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 10
          submodules: true

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: ./#source/scss/style.scss
          destination: css/style.css

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
